### PR TITLE
Fix Unifi DB creation in InfluxDB

### LINKED ISSUE #151: Unifi database not created in InfluxDB
# Issue Template

## Description
When creating the Unifi jail w/ integrated Controller, the unifi database is not being created in Influx.

### Steps to Reproduce

1. Create Influx jail and Unifi Jail 
2.  Observe no unifi database being created
3.  

Noticed this when testing Grafana. I'll take a look when I get to the Unifi fixes.

### LINKED ISSUE #181: Update error in jailman.sh
# Issue Template

## Description

The jailman.sh script contains errors in the update section

### Detailed Bug Report
Line 199 references ```"${SCRIPT_DIR}"/jails/"${!blueprint}"/update.sh ``` folder and should be ```"${SCRIPT_DIR}"/blueprints/"${!blueprint}"/update.sh```

That line is also missing ```"${jail}"``` at the end.

### Steps to Reproduce
Please enter the steps to reproduce the bug or behaviour:  

1.  
2.  
3.

### PR DESCRIPTION
**Pull request by colemamd**
# Pull Request Template

### Purpose:
Fixes #151 Closes #151 

Edit:
Also Fixes #181 

### Notes:
Makes unifi_poller a boolean value, as described in the readme. poller will not install unless unifi_poller is true.

### Please make sure you have followed the self checks below before submitting a PR:

- [ x] Code is sufficiently commented
- [ x] Code is indented with tabs and not spaces
- [ x] The PR does not bring up any new errors
- [ x] The PR has been tested
- [ ] Any new files are named using lowercase (to avoid issues on case sensitive file systems)

### CODE REVIEW

File: blueprints/unifi/update.sh [hunk 1]
```diff
@@ -2,25 +2,28 @@
 # This file contains the update script for unifi
 # Unifi Controller is updated through pkg, Unifi-Poller is not. This script updates Unifi-Poller
 
-if [[ ! "${!POLLER}" ]]; then
-	echo "Skipping Unifi Poller for update, not installed"
+POLLER="jail_${1}_unifi_poller"
+
+# shellcheck disable=SC2154
+if [ "${!POLLER}" = true ]; then
```
Comment (Ornias1993) [inline blueprints/unifi/update.sh:8]: I think we should use string comparison here:
```suggestion
if [ "${!POLLER}" == true ]; then	
```

File: blueprints/unifi/install.sh [hunk 2]
```diff
@@ -63,10 +63,7 @@ iocage exec "${1}" sysrc unifi_enable=YES
 iocage exec "${1}" service unifi start
 
 # shellcheck disable=SC2154
-if [[ ! "${!POLLER}" ]]; then
-  echo "Installation complete!"
-  echo "Unifi Controller is accessible at https://${JAIL_IP}:8443."
-else
+if [ "${!POLLER}" = true ]; then
```
Comment (Ornias1993) [inline blueprints/unifi/install.sh:66]: I think we should use string comparison here:
```suggestion
if [ "${!POLLER}" == true ]; then	
```

**Comment by colemamd** [comment]
Didn't know if you wanted to fix the line in jailman, which is why I created the issue instead of just issuing a pr against it, but as you said, its small and easy fix
